site_name: lsof
theme:
  name: readthedocs
  highlightjs: true
nav:
  - index.md
  - getting-started.md
  - tutorial.md
  - hang.md
  - options.md
  - faq.md
  - manpage.md
plugins:
  - search
markdown_extensions:
  - admonition