# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  ubuntu2204:
    machine:
      image: ubuntu-2204:2022.10.2 
  debian11:
    docker:
      - image: docker.io/debian:11
  fedora36:
    docker:
      - image: docker.io/fedora:36
  fedora37:
    docker:
      - image: docker.io/fedora:37
  centos8:
    docker:
      - image: quay.io/centos/centos:stream8
  centos9:
    docker:
      - image: quay.io/centos/centos:stream9

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  linux:
    parameters:
      distro:
        type: executor
    executor: << parameters.distro >>
    steps:
      - run:
          name: Install build tools
          command: |
            dnf -y install git gcc make sudo nmap-ncat iproute procps autoconf automake pkg-config || true
            dnf -y install libtirpc-devel || true
            apt update || true
            apt install -y git gcc make sudo ncat iproute2 procps autoconf automake libtirpc-dev groff pkg-config || true
      - when:
          condition:
            equal: [ fedora36, << parameters.distro >> ]
          steps:
            - run:
                command: |
                  dnf -y install lcov gem procps python3-pip
                  pip3 install --user cpp-coveralls
      - checkout
      - run:
          name: Configure
          command: |
            ./Configure -n linux
      - when:
          condition:
            equal: [ fedora36, << parameters.distro >> ]
          steps:
            - run:
                name: Build
                command: |
                  CC="cc"
                  CC_EXTRA="--coverage"
                  make -j 2 CDEF="${CC_EXTRA}" CC="${CC} ${CC_EXTRA}"
      - when:
          condition:
            not:
              equal: [ fedora36, << parameters.distro >> ]
          steps:
            - run:
                name: Build
                command: |
                  make -j 2
      - run:
          name: Test
          command: |
            bash ./check.bash linux
      - when:
          condition:
            equal: [ fedora36, << parameters.distro >> ]
          steps:
            - run:
                name: Report coverage
                command: |
                  lcov -c -b . -d . -o coverage.info
                  /root/.local/bin/coveralls --root .
      - run:
          name: Build and test using autotools
          command: |
            git clean -fdx .
            autoreconf -vif
            ./configure
            make
            sudo make install
            make check
            cat test-suite.log
            make distcheck
  bigsur:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Install pkg-config
          command: |
            brew install pkg-config
      - run:
          name: Configure
          command: |
            LSOF_INCLUDE=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include ./Configure -n darwin
      - run:
          name: Build
          command: |
            make -j 2
      - run:
          name: Test
          command: |
            bash ./check.bash darwin
      - run:
          name: Build using autotools
          command: |
            git clean -fdx .
            autoreconf -vif
            ./configure
            make
            make install
            make check
      - run:
          name: Rebuild and test using distribution tarball
          command: |
            make dist
            mkdir temp
            cd temp
            tar xvf ../lsof-*.tar.gz
            cd lsof-*
            ./configure
            make
            make install
            make check

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  gnulinux-workflow:
    jobs:
      - linux:
          matrix:
            parameters:
              distro: [fedora36, fedora37, centos8, centos9, debian11, ubuntu2204]
      - bigsur
